# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

  # Pods for FirebaseProject


 pod 'Firebase/Analytics'
 pod 'Firebase/Auth'
 pod 'Firebase/Core'
 pod 'Firebase/Firestore'
 pod 'Firebase/Storage'
 pod 'Kingfisher', '~> 5.0'

end
